# WWW
[[redirects]]
  from = "https://www.clevertech.be/"
  to = "https://clevertech.be/"
  status = 301
  force = false
# Netlify
[[redirects]]
  from = "https://clevertech.netlify.app"
  to = "https://clevertech.be/"
  status = 301
  force = false
# 404
[[redirects]]
from = "*"
to = "/404"
status = 404
# Plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
