export const filters = [
  'articles.filter.topic.1',
  'articles.filter.topic.2',
  'articles.filter.topic.3',
  'articles.filter.topic.4',
  'articles.filter.topic.5',
]

export const allArticles = [
  {
    name: 'article1',
    title: 'article1.title',
    shortDescription: 'article1.shortDescription',
    description: 'article1.description',
    text: 'article1.text',
    location: 'Wemmel, Brussels',
    author: 'Hamza Mounir',
    date: '16/10/2023',
    image: '/images/article/article1.jpg',
    link: '/blog/article1',
    topic: 'articles.filter.topic.1',
  },
  {
    name: 'article2',
    title: 'article2.title',
    shortDescription: 'article2.shortDescription',
    description: 'article2.description',
    text: 'article2.text',
    location: 'Wemmel, Brussels',
    author: 'Hamza Mounir',
    date: '16/10/2023',
    image: '/images/article/article2.jpg',
    link: '/blog/article2',
    topic: 'articles.filter.topic.2',
  },
  {
    name: 'article3',
    title: 'article3.title',
    shortDescription: 'article3.shortDescription',
    description: 'article3.description',
    text: 'article3.text',
    location: 'Wemmel, Brussels',
    author: 'Hamza Mounir',
    date: '16/10/2023',
    image: '/images/article/article3.jpg',
    link: '/blog/article3',
    topic: 'articles.filter.topic.3',
  },
]
