export const allProjects = [
  {
    name: 'project1',
    title: 'project.1.title',
    shortDescription: 'project.1.shortDescription',
    description: 'project.1.description',
    image: '/images/project/lb.png',
    galleryBrand: [],
    galleryWeb: [],
    link: '/projects/project1',
    label: 'projects.label.ui',
    features: ['features.1.feature1', 'features.1.feature2', 'features.1.feature3'],
  },
  {
    name: 'project2',
    title: 'project.2.title',
    shortDescription: 'project.2.shortDescription',
    description: 'project.2.description',
    galleryBrand: [],
    galleryWeb: [],
    image: '/images/project/medistia.png',
    link: '/projects/project2',
    label: 'projects.label.ui',
    features: ['features.2.feature1', 'features.2.feature2', 'features.2.feature3'],
  },
  {
    name: 'project3',
    title: 'project.3.title',
    shortDescription: 'project.3.shortDescription',
    description: 'project.3.description',
    galleryBrand: [],
    galleryWeb: [],
    image: '/images/project/premierArt.png',
    link: '/projects/project3',
    label: 'projects.label.ui',
    features: ['features.3.feature1', 'features.3.feature2', 'features.3.feature3'],
  },
  {
    name: 'project4',
    title: 'project.4.title',
    shortDescription: 'project.4.shortDescription',
    description: 'project.4.description',
    galleryBrand: [],
    galleryWeb: [],
    image: '/images/project/rtb.png',
    link: '/projects/project4',
    label: 'projects.label.ui',
    features: ['features.4.feature1', 'features.4.feature2', 'features.4.feature3'],
  },
]
