export const services = [
  {
    title: 'service.1.title',
    description: 'service.1.description',
    icon: '/icons/services/1.svg',
    link: '/services#service1',
    image: '/images/services/1.svg',
    cta: 'service.1.cta',
    features: ['service.1.feature1', 'service.1.feature2', 'service.1.feature3'],
  },
  {
    title: 'service.2.title',
    description: 'service.2.description',
    icon: '/icons/services/2.svg',
    link: '/services#service2',
    image: '/images/services/2.svg',
    cta: 'service.2.cta',
    features: ['service.2.feature2', 'service.2.feature4', 'service.2.feature3'],
  },
  {
    title: 'service.3.title',
    description: 'service.3.description',
    icon: '/icons/services/3.svg',
    link: '/services#service3',
    image: '/images/services/3.svg',
    cta: 'service.3.cta',
    features: ['service.3.feature2', 'service.3.feature4', 'service.3.feature3'],
  },
  {
    title: 'service.4.title',
    description: 'service.4.description',
    icon: '/icons/services/4.svg',
    link: '/services#service4',
    image: '/images/services/4.svg',
    cta: 'service.4.cta',
    features: ['service.4.feature2', 'service.4.feature4', 'service.4.feature3'],
  },
  {
    title: 'service.5.title',
    description: 'service.5.description',
    icon: '/icons/services/5.svg',
    link: '/services#service5',
    image: '/images/services/5.svg',
    cta: 'service.5.cta',
    features: ['service.5.feature2', 'service.5.feature4', 'service.5.feature3'],
  },
  {
    title: 'service.6.title',
    description: 'service.6.description',
    icon: '/icons/services/6.svg',
    link: '/services#service6',
    image: '/images/services/6.svg',
    cta: 'service.6.cta',
    features: ['service.6.feature2', 'service.6.feature4', 'service.6.feature3'],
  },
  {
    title: 'service.7.title',
    description: 'service.7.description',
    icon: '/icons/services/7.svg',
    link: '/services#service7',
    image: '/images/services/7.svg',
    cta: 'service.7.cta',
    features: ['service.7.feature2', 'service.7.feature4', 'service.7.feature3'],
  },
  {
    title: 'service.8.title',
    description: 'service.8.description',
    icon: '/icons/services/8.svg',
    link: '/services#service8',
    image: '/images/services/8.svg',
    cta: 'service.8.cta',
    features: ['service.8.feature2', 'service.8.feature4', 'service.8.feature3'],
  },
]
