export const services = [
  {
    title: 'service.1.title',
    description: 'service.1.description',
    icon: '/icons/services/1.svg',
    link: '/services#service1',
    image: '/images/feature.png',
    cta: 'service.1.cta',
    features: ['service.1.feature1', 'service.1.feature2', 'service.1.feature3'],
  },
  {
    title: 'service.2.title',
    description: 'service.2.description',
    icon: '/icons/services/1.svg',
    link: '/services#service2',
    image: '/images/feature.png',
    cta: 'service.2.cta',
    features: ['service.2.feature2', 'service.2.feature4', 'service.2.feature3'],
  },
  {
    title: 'service.3.title',
    description: 'service.3.description',
    icon: '/icons/services/1.svg',
    link: '/services#service3',
    image: '/images/feature.png',
    cta: 'service.3.cta',
    features: ['service.3.feature2', 'service.3.feature4', 'service.3.feature3'],
  },
  {
    title: 'service.4.title',
    description: 'service.4.description',
    icon: '/icons/services/1.svg',
    link: '/services#service4',
    image: '/images/feature.png',
    cta: 'service.4.cta',
    features: ['service.4.feature2', 'service.4.feature4', 'service.4.feature3'],
  },
]
